# Generated static library file name
NAME := liblvgl

OBJDIR := ../obj

# Source files to build
C_SRC += \
		$(sort $(wildcard src/*.c)) \
			$(sort $(wildcard src/core/*.c)) \
			$(sort $(wildcard src/display/*.c)) \
			$(sort $(wildcard src/draw/*.c)) \
			$(sort $(wildcard src/draw/sw/*.c)) \
			$(sort $(wildcard src/draw/sw/blend/*.c)) \
			$(sort $(wildcard src/font/*.c)) \
			$(sort $(wildcard src/indev/*.c)) \
			$(sort $(wildcard src/layouts/*.c)) \
			$(sort $(wildcard src/layouts/flex/*.c)) \
			$(sort $(wildcard src/layouts/grid/*.c)) \
			$(sort $(wildcard src/libs/barcode/*.c)) \
			$(sort $(wildcard src/libs/bin_decoder/*.c)) \
			$(sort $(wildcard src/libs/bmp/*.c)) \
			$(sort $(wildcard src/libs/ffmpeg/*.c)) \
			$(sort $(wildcard src/libs/freetype/*.c)) \
			$(sort $(wildcard src/libs/fsdrv/*.c)) \
			$(sort $(wildcard src/libs/gif/*.c)) \
			$(sort $(wildcard src/libs/libjpeg_turbo/*.c)) \
			$(sort $(wildcard src/libs/libpng/*.c)) \
			$(sort $(wildcard src/libs/lodepng/*.c)) \
			$(sort $(wildcard src/libs/lz4/*.c)) \
			$(sort $(wildcard src/libs/qrcode/*.c)) \
			$(sort $(wildcard src/libs/rle/*.c)) \
			$(sort $(wildcard src/libs/rlottie/*.c)) \
			$(sort $(wildcard src/libs/thorvg/*.c)) \
			$(sort $(wildcard src/libs/tiny_ttf/*.c)) \
			$(sort $(wildcard src/libs/tjpg/*.c)) \
			$(sort $(wildcard src/misc/*.c)) \
			$(sort $(wildcard src/misc/cache/*.c)) \
			$(sort $(wildcard src/osal/*.c)) \
			$(sort $(wildcard src/stdlib/*.c)) \
			$(sort $(wildcard src/stdlib/builtin/*.c)) \
			$(sort $(wildcard src/themes/*.c)) \
			$(sort $(wildcard src/themes/default/*.c)) \
			$(sort $(wildcard src/themes/mono/*.c)) \
			$(sort $(wildcard src/themes/simple/*.c)) \
			$(sort $(wildcard src/tick/*.c)) \
			$(sort $(wildcard src/widgets/*.c)) \
			$(sort $(wildcard src/widgets/animimage/*.c)) \
			$(sort $(wildcard src/widgets/arc/*.c)) \
			$(sort $(wildcard src/widgets/bar/*.c)) \
			$(sort $(wildcard src/widgets/button/*.c)) \
			$(sort $(wildcard src/widgets/buttonmatrix/*.c)) \
			$(sort $(wildcard src/widgets/calendar/*.c)) \
			$(sort $(wildcard src/widgets/canvas/*.c)) \
			$(sort $(wildcard src/widgets/chart/*.c)) \
			$(sort $(wildcard src/widgets/checkbox/*.c)) \
			$(sort $(wildcard src/widgets/dropdown/*.c)) \
			$(sort $(wildcard src/widgets/image/*.c)) \
			$(sort $(wildcard src/widgets/imagebutton/*.c)) \
			$(sort $(wildcard src/widgets/keyboard/*.c)) \
			$(sort $(wildcard src/widgets/label/*.c)) \
			$(sort $(wildcard src/widgets/led/*.c)) \
			$(sort $(wildcard src/widgets/line/*.c)) \
			$(sort $(wildcard src/widgets/list/*.c)) \
			$(sort $(wildcard src/widgets/lottie/*.c)) \
			$(sort $(wildcard src/widgets/menu/*.c)) \
			$(sort $(wildcard src/widgets/msgbox/*.c)) \
			$(sort $(wildcard src/widgets/objx_templ/*.c)) \
			$(sort $(wildcard src/widgets/property/*.c)) \
			$(sort $(wildcard src/widgets/roller/*.c)) \
			$(sort $(wildcard src/widgets/scale/*.c)) \
			$(sort $(wildcard src/widgets/slider/*.c)) \
			$(sort $(wildcard src/widgets/span/*.c)) \
			$(sort $(wildcard src/widgets/spinbox/*.c)) \
			$(sort $(wildcard src/widgets/spinner/*.c)) \
			$(sort $(wildcard src/widgets/switch/*.c)) \
			$(sort $(wildcard src/widgets/table/*.c)) \
			$(sort $(wildcard src/widgets/tabview/*.c)) \
			$(sort $(wildcard src/widgets/textarea/*.c)) \
			$(sort $(wildcard src/widgets/tileview/*.c)) \
			$(sort $(wildcard src/widgets/win/*.c))


# Generate a static library in the makefile folder
TARGET_TYPE := lib

# Boilerplate.mk contains all rules to build makefiles for NetBurner devices
include $(NNDK_ROOT)/make/boilerplate.mk